[package]
name = "tracing-forest"
version = "0.1.0"
authors = ["Quinn Okabayashi"]
edition = "2018"
description = "Placeholder for future project"
repository = "https://github.com/QnnOkabayashi/tracing-forest"
license = "MIT"

[dependencies]
