[package]
name = "tracing-forest-macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[features]
sync = []
derive = []
attributes = []

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"

[dependencies.syn]
version = "1.0"
features = ["derive", "parsing"]